services:
  bot:
    build: .
    container_name: telebot
    restart: always
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - bot_network

  mongo:
    image: mongo:6.0
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge

volumes:
  mongo_data: